apiVersion: v1
kind: Namespace
metadata:
  name: ping-monitor
---
apiVersion: v1
kind: Secret
metadata:
  name: ping-monitor-api-secrets
  namespace: ping-monitor
type: Opaque
stringData:
  RAILS_MASTER_KEY: "op://Private/ping_monitor_deployment/RAILS_MASTER_KEY"
  JWT_SECRET_KEY: "op://Private/ping_monitor_deployment/JWT_SECRET_KEY"
  DATABASE_URL: "op://Private/ping_monitor_deployment/API_DATABASE_URL"
